#!/bin/busybox sh
#
# Gentoo Custom Initramfs - Detached LUKS Header
# Lenovo LOQ - NVMe + External USB for secrets
#

GENTOO_MAPPER="/dev/mapper/gentoo"
SECRETS_MAPPER="/dev/mapper/secrets"
BTRFS_SUBVOLS="@root:root @home:home @usr:usr @var:var @opt:opt"

msg() {
    printf '\033[1;32m>>>\033[0m %s\n' "$1"
}

warn() {
    printf '\033[1;33m[!]\033[0m %s\n' "$1"
}

err() {
    printf '\033[1;31m[ERROR]\033[0m %s\n' "$1"
}

find_crypt_nvme() {
    # Acha o NVMe correto pelo serial
    for dev in /sys/class/nvme/nvme*; do
    serial=$(cat "$dev/serial" | tr -d ' ')
    if [ "$serial" = "S5GXNF0R856448H" ]; then
        CRYPT_DEV="/dev/$(basename $dev)n1"
        break
    fi
done

    if [ -z "$CRYPT_DEV" ]; then
    	rescue_shell "Crypt device not found!"
    fi
}

rescue_shell() {
    err "${1:-Erro desconhecido. Entrando em shell de recuperação...}"
    echo ""
    echo "Comandos úteis:"
    echo "  blkid                    - listar dispositivos"
    echo "  cryptsetup luksDump      - verificar header LUKS"
    echo "  cat /proc/partitions     - ver partições detectadas"
    echo ""

    # Functional shell
    busybox --install -s
    exec setsid cttyhack /bin/sh
}

# Mount virtual filesystems
mount -t devtmpfs none /dev || rescue_shell "Falha ao montar /dev"
mount -t proc none /proc || rescue_shell "Falha ao montar /proc"
mount -t sysfs none /sys || rescue_shell "Falha ao montar /sys"

# Redirect I/O for console
exec 0</dev/console
exec 1>/dev/console
exec 2>/dev/console

# Write /dev/disk/* with mdev or manual links
#if command -v mdev >/dev/null 2>&1; then
#    mdev -d &
#    mdev -s
#fi

# Wait for disks
sleep 5

# CABECALHO
clear
echo ""
echo "========================================"
echo "  Gentoo Linux - Encrypted Boot"
echo "  Lenovo LOQ Custom Initramfs"
echo "========================================"
echo ""

# GLOBAL VARIABLES
#EFI=`findfs UUID=9F38-6F64`
#SECRETS=`findfs UUID=ad152456-8be9-4a39-be8c-4884bdef1ef2`

# DECRYPT SECRETS DISK
echo ""
msg "Descriptografando o disco SECRETS"

cryptsetup luksOpen /dev/sda1 secrets || rescue_shell "Nao foi possivel descriptografar secrets"
mount -o ro "$SECRETS_MAPPER" /mnt/secrets || rescue_shell "Falha ao montar USB"

[ -f /mnt/secrets/.cache/cache.dat ] || rescue_shell "cache.dat nao encontrado no USB"
[ -f /mnt/secrets/.cache/index.dat ] || rescue_shell "index.dat nao encontrado no USB"

msg "Arquivos de segredos encontrados"
echo ""

# DECRYPT SYSTEM
echo ""
msg "Abrindo particao criptografada com detached header..."

#find_crypt_nvme
cryptsetup --header /mnt/secrets/.cache/index.dat \
--key-file /mnt/secrets/.cache/cache.dat \
luksOpen /dev/nvme1n1p2 gentoo || rescue_shell "nao foi possivel descriptografar o sistema"
msg "Particao aberta: $GENTOO_MAPPER"
echo ""

# UMOUNT SECRETS DEVICE
echo ""
msg "Desmontando o dispositivo USB SECRETS..."

umount /mnt/secrets || warn "Aviso: falha ao desmontar USB"
cryptsetup close secrets || warn "Aviso: falha ao fechar $SECRETS_MAPPER"

msg "USB pode ser removido com seguranca"
echo ""

# MOUNT ROOT FILESYSTEM
echo ""
msg "Montando sistema de arquivos root..."

# Mount default subvolume
if ! mount -t btrfs -o ro "$GENTOO_MAPPER" /newroot; then
    rescue_shell "Falha ao montar root filesystem"
fi

# Create mountpoints for subvolumes if they don't exist
for subvol_entry in $BTRFS_SUBVOLS; do
    mountpoint="${subvol_entry#*:}"
    mkdir -p "/newroot/$mountpoint"
done

# Mount each subvolumes
for subvol_entry in $BTRFS_SUBVOLS; do
    subvol="${subvol_entry%%:*}"
    mountpoint="${subvol_entry#*:}"
    
    if ! mount -t btrfs -o ro,subvol="$subvol" "$GENTOO_MAPPER" "/newroot/$mountpoint" 2>/dev/null; then
        warn "Aviso: falha ao montar subvolume $subvol em /$mountpoint"
    fi
done

msg "Subvolumes btrfs montados com sucesso"
echo ""

# MOUNT EFI PARTITION
echo ""
msg "Montando sistemas de arquivos EFI..."
mount -t vfat -o ro /dev/nvme1n1p1 /newroot/boot/efi

msg "Partica££o EFI montado com sucesso"
echo ""

# SWITCH ROOT
echo ""
msg "Transferindo controle para o sistema..."
echo ""

# Umount the /sys, /proc and /dev mountpoints os subvolume /sys, /proc e /dev
umount /sys
umount /proc
mount --move /dev /newroot/dev

# Executa switch_root
exec switch_root /newroot /sbin/init || rescue_shell "switch_root falhou"
